### ISSUE TITLE
[Member] 환경 설정 변경

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#100]
### Describe

프로젝트 이름을 변경함에 따라 필요한 환경 설정을 변경합니다.

### Tasks

- [x] `PLAY` -> `Members`
- [x] alias (@/) 추가
- [x] 서드파티 앱 환경변수 설정
- [x] `production` 환경에서 에러 메세지 숨기기
- [x] 실험 및 개발 기능 숨기기
