### ISSUE TITLE
[Member] BUG-[25, 26, 33]

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#106]
### Describe

도서 관련 버그를 개선합니다.

### Tasks

- [x] BUG-25 도서 대여 연장 제한
- [x] BUG-26 도서 패널에 반납 관련 반영 안 됨
- [x] BUG-33 도서 대여 불가
