### ISSUE TITLE
게시글 사용자 피드백 개선 (OPEN-BETA)

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#119]
### Describe

운영진 오픈 베타 피드백에서 제시된 게시글 개선사항을 작업합니다.

### Tasks

- [x] 글쓰기 버튼을 찾기가 어려워요.
- [x] 신고가 무제한으로 돼요.
- [x] 게시글이나 댓글 작성시 학번 정보가 전부 노출 돼요 (개인정보 보호 및 악용 방지)
- [x] 프로필 사진이 영역을 벗어나요. (overflow)
- [x] 게시글에 이전 및 이후 게시글 정보를 표시하면 좋을 거 같아요.
- [ ] ~~게시글에 이미지 및 파일을 첨부 할 수 있으면 좋을 거 같아요.~~

### ETC

게시글에 이미지나 파일 첨부하는 기능은 `Feature 1.1` 에서 개발 예정입니다.
