### ISSUE TITLE
BUG-(36~41) 버그 

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#121]
### Describe

BUG-(36~41)를 개선합니다.

### Tasks

- [x] 알림 업데이트 시간 표시 (BUG-36)
- [x] 도서 패널 기간 표시 (BUG-38)
- [x] 활동 패널 타이틀 오버플로우 (BUG-40)
- [x] 신청서 작성 후 폼 초기화 (BUG-37)
- [x] 회비 반려 버튼 미표시 (BUG-41)
- [x] 프로필 삭제 미반영 (BUG-39)
