### ISSUE TITLE
[Member] API Call 최적화

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#152]
### Describe

- TanStack Query의 Query Key를 Query Key Factory를 통해서 보다 편의성 있게 관리 되도록 개선합니다.
- Query Caching을 통하여 API Call을 최소화 합니다.

### Tasks

- [x] API Hook 폴더 구조화
- [x] Query Key Factory
- [x] `staleTime`과 `gcTime`을 적절하게 설정하여 API Call을 최소화 합니다.

### ETC

- staleTime: 기본으로 10분으로 설정합니다.
- 사용자가 이용에 최신 데이터가 불필요한 경우: 1시간
- gcTime은 staleTime의 2배로 지정합니다.
