### ISSUE TITLE
[Status] 스테이터스 페이지 개발

### ISSUE THREAD

**Issue by SWARVY** [KGU-C-Lab/clab.page#171]
### Describe

점검 및 운영 현황 확인을 위한 status 페이지 개발

### Tasks

- [x] Next 14로 프로젝트 세팅
- [x] FSD 아키텍쳐를 사용하여 임시적으로 점검 페이지(스테이터스 페이지) 개발
- [x] 로티를 적용하여 디자인 구성
- [x] 백엔드 api 연동
- [x] 레이아웃 보완
