### ISSUE TITLE
Login System Migration

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#25]
### Describe

기존 JS로 작성된 프로젝트를 TS, Monorepo 환경으로 마이그레이션합니다.

### Tasks

> 새로운 OAuth 시스템으로 apps/auth에 설계합니다.

- [x] Next.js 환경 세팅
- [x] 기존 시스템 마이그레이션
- [x] 새로인 시스템 기획안에 따라 1차 MVP
