### ISSUE TITLE
BUG-(7, 8, 10, 14) 버그 개선

### ISSUE THREAD

**Issue by gwansikk** [KGU-C-Lab/clab.page#67]
### Describe

open-beta를 위해 진행한 테스트에서 확인된 버그를 개선합니다.

### Task

- [x] 도서 반납 후 리스트 리패치 (BUG-7)
- [x] 도서 상세 페이지 내 대출 내역 조회 (BUG-8)
- [x] 회비 사용 요청 (BUG-10)
- [x] 배너 시스템 설정 기능 (BUG-14)
